### ISSUE TITLE
Official Plugin

### ISSUE THREAD

**Issue by kbrsh** [shff/parcel-plugin-moon#2]
Hey! I'm the creator of Moon :)

I really appreciate you making this plugin — thanks for your hard work. For Moon v1 (which is coming soon), the official CLI template will use Parcel. I'd like to publish an official Moon parcel plugin but it requires a new syntax not supported by this plugin.

I'd love it if you could transfer ownership of the npm package `parcel-plugin-moon` to my NPM username `@kingkabir`.

```sh
npm owner add kingkabir parcel-plugin-moon
npm owner rm shferreira parcel-plugin-moon
```

Thanks once again.

**Comment by kbrsh** [comment]
@shff Just wanted to follow up — I've written the new plugin at [kbrsh/parcel-plugin-moon](https://github.com/kbrsh/parcel-plugin-moon).

**Comment by shff** [comment]
@kbrsh Ooops, I must have missed the notification! I just transfered the package to you! Sorry about the delay!!!

**Comment by kbrsh** [comment]
No problem, thanks for getting to it :)
